apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-inspector-gadget-approuting
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inspectorgadget
            port:
              number: 80
