apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-echo-server-approuting
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: websocket-echo-server
            port:
              number: 80
        path: /
        pathType: Prefix