apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-echo-server-agc
  annotations:
    alb.networking.azure.io/alb-id: "/subscriptions/dcef7009-6b94-4382-afdc-17eb160d709a/resourceGroups/rg-aks-agc-agic-270/providers/Microsoft.ServiceNetworking/trafficControllers/agc-aks"
    alb.networking.azure.io/alb-frontend: "agc-frontend"
spec:
  ingressClassName: azure-alb-external
  rules:
  - host: d2c0atfrduabfgaf.fz33.alb.azure.com
    http:
      paths:
      - path: /websocket-echo-server
        pathType: Prefix
        backend:
          service:
            name: websocket-echo-server
            port:
              number: 80
---
# https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/websockets#health-probes
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: websockets-health-check-policy
  namespace: default
spec:
  targetRef:
    group: ""
    kind: Service
    name: websocket-echo-server
    namespace: default
  default:
    interval: 5s
    timeout: 3s
    healthyThreshold: 1
    unhealthyThreshold: 1
    http:
      path: /health 