apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app01
  namespace: argocd
spec:
  project: project-apps
  source:
    path: 291_gitops_argocd_helm/helm
    repoURL: https://github.com/HoussemDellai/aks-course/
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: app02
    server: https://kubernetes.default.svc